// <auto-generated />
using System.CodeDom.Compiler;
using System.Data.Entity.Migrations;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

[GeneratedCode("EntityFramework.Migrations", "6.4.4")]
public sealed partial class UserAdd : IMigrationMetadata
{
    private readonly ResourceManager Resources = new ResourceManager(typeof(UserAdd));
    
    string IMigrationMetadata.Id
    {
        get { return "202402141157287_UserAdd"; }
    }
    
    string IMigrationMetadata.Source
    {
        get { return Resources.GetString("Source"); }
    }
    
    string IMigrationMetadata.Target
    {
        get { return Resources.GetString("Target"); }
    }
}
